#!/bin/sh
#
# example for start script for MovSim core, see http://www.movsim.org
# please specify your path to the target output folder and the target version
#

cd "${0%/*}" # Switch to directory of script
java -jar ./movsim/core/target/MovsimCore-1.7.0-SNAPSHOT-jar-with-dependencies.jar -o movsim_output $@


